# Generated by Django 5.0.6 on 2024-05-24 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150, verbose_name='UserName')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idModerator', models.PositiveIntegerField(default=0, verbose_name='ID Modearador')),
                ('moderatorName', models.CharField(max_length=150, verbose_name='ModeratorName')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phoneNumber', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.PositiveIntegerField(default=0)),
                ('reserveDetail', models.CharField(max_length=200, verbose_name='ReserveDetail')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150, verbose_name='VcName')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localName', models.CharField(max_length=150, verbose_name='LocalName')),
                ('localAddress', models.CharField(max_length=500, verbose_name='LocalAddress')),
                ('localCapacity', models.PositiveBigIntegerField(default=0)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moderator')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcName', models.CharField(max_length=150, verbose_name='VcName')),
                ('vcMotive', models.CharField(max_length=200, verbose_name='VcMotive')),
                ('url', models.URLField()),
                ('platafom', models.CharField(max_length=150)),
                ('weCreators', models.BooleanField(default=False, verbose_name='Somos Creadores?')),
                ('dateTime', models.DateTimeField(auto_now=True, verbose_name='DateTime')),
                ('duration', models.TimeField(auto_now=True, verbose_name='Duration')),
                ('cantpart', models.PositiveSmallIntegerField(default=0, verbose_name='Cantidad  de Participantes')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('calendary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calendary')),
                ('idofModerator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.moderator')),
            ],
        ),
    ]
