# Generated by Django 5.0.6 on 2024-05-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='calendary',
        ),
        migrations.DeleteModel(
            name='Calendary',
        ),
    ]
