# Generated by Django 5.0.6 on 2024-05-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_reserve_calendary_delete_calendary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='idModerator',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
